server:
  port: 18080
  servlet:
    encoding:
      charset: UTF-8
      force: true

---
spring:
  config:
    activate:
      on-profile: loc
---
## active profile : dev
spring:
  config:
    activate:
      on-profile: dev
---
## active profile : prod
spring:
  config:
    activate:
      on-profile: prod
---


